# This is a placeholder for future development. It is intended to allow other
# nodes to configure devices and interfaces, should that become necessary.

# Request types
# *****************************************************************************
bool read_pin                     = true    # Read data on pin(s)
bool write_pin                    = false    # Write data to pin(s)

# If error == true, check strerr for more info.

# Data transferred in ROS
# *****************************************************************************
bool read_write     # Type of request.
uint8 data_format   # Format for the data array and the data in it.
uint8[] pin         # Interface pin number of request.
float[] data        # A value to write to pins.
---
float[] values      # If data is read, these are the values requested
bool error          # Error/success number
string strerr       # Printable error description
